serverAddr = "114.215.164.199"
serverPort = 20050
auth.method = "token"
auth.token = "HJGHJKGjhgkjhghjgGhj"

[[proxies]]
name = "ceramic"
type = "tcp"
localIP = "127.0.0.1"
localPort = 9357
remotePort = 20048
